fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,10 +43,15 @@ jobs:
           ping -c 2 ${{ secrets.SSH_HOST }} || echo "Ping failed"
           nc -zv ${{ secrets.SSH_HOST }} 22 || echo "Port 22 unreachable"
 
-      - name: Add SSH server to known_hosts
+      # - name: Add SSH server to known_hosts
+      #   run: |
+      #     ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+      - name: Verbose ssh-keyscan debug
         run: |
-          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
-
+          mkdir -p ~/.ssh
+          echo "Trying ssh-keyscan -H -T 15 -v ${{ secrets.SSH_HOST }}"
+          ssh-keyscan -H -T 15 -v ${{ secrets.SSH_HOST }} || echo "::warning:: ssh-keyscan failed"
+          
       - name: SCP docker-compose.${{ inputs.env }}.yml to server
         run: |
           scp docker-compose.${{ inputs.env }}.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/${{ inputs.env }}/.
