fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,21 +37,24 @@ jobs:
           echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
-      - name: Debug SSH host resolution
-        run: |
-          echo "Testing SSH_HOST: ${{ secrets.SSH_HOST }}"
-          ping -c 2 ${{ secrets.SSH_HOST }} || echo "Ping failed"
-          nc -zv ${{ secrets.SSH_HOST }} 22 || echo "Port 22 unreachable"
+      - name: Add SSH server to known_hosts
+        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
 
-      # - name: Add SSH server to known_hosts
+      # - name: Debug SSH host resolution
       #   run: |
-      #     ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
-      - name: Verbose ssh-keyscan debug
-        run: |
-          mkdir -p ~/.ssh
-          echo "Trying ssh-keyscan -H -T 15 -v ${{ secrets.SSH_HOST }}"
-          ssh-keyscan -H -T 15 -v ${{ secrets.SSH_HOST }} || echo "::warning:: ssh-keyscan failed"
-          
+      #     echo "Testing SSH_HOST: ${{ secrets.SSH_HOST }}"
+      #     ping -c 2 ${{ secrets.SSH_HOST }} || echo "Ping failed"
+      #     nc -zv ${{ secrets.SSH_HOST }} 22 || echo "Port 22 unreachable"
+
+      # # - name: Add SSH server to known_hosts
+      # #   run: |
+      # #     ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+      # - name: Verbose ssh-keyscan debug
+      #   run: |
+      #     mkdir -p ~/.ssh
+      #     echo "Trying ssh-keyscan -H -T 15 -v ${{ secrets.SSH_HOST }}"
+      #     ssh-keyscan -H -T 15 -v ${{ secrets.SSH_HOST }} || echo "::warning:: ssh-keyscan failed"
+
       - name: SCP docker-compose.${{ inputs.env }}.yml to server
         run: |
           scp docker-compose.${{ inputs.env }}.yml ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/${{ inputs.env }}/.
