fix

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -38,7 +38,9 @@ jobs:
           chmod 600 ~/.ssh/id_rsa
 
       - name: Add SSH server to known_hosts
-        run: ssh-keyscan -H -p 22 ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+        run: |
+          mkdir -p ~/.ssh
+          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts || echo "ssh-keyscan failed"
 
       - name: SCP docker-compose.${{ inputs.env }}.yml to server
         run: |
